import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@/styles/globals.css'
import {NavBar} from "@/components/NavBar";
import {Toaster} from "@/components/ui/toaster";
import {AuthProviderSession} from "@/components/SessionProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProviderSession>
          {/*<ThemeProvider*/}
          {/*    attribute="class"*/}
          {/*    defaultTheme="system"*/}
          {/*    enableSystem*/}
          {/*    disableTransitionOnChange*/}
          {/*>*/}
          <main className='h-screen flex flex-col justify-center items-center'>
              <NavBar/>
              {children}
          </main>
              {/*</ThemeProvider>*/}
          <Toaster/>
      </AuthProviderSession>
      </body>
    </html>
  )
}
